name: Publish Website to cPanel

on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    name: FTP Deploy Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}  # Use 'server' instead of 'ftp-server'
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
