name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Package application
        run: zip -r lambda.zip . -x node_modules/\*

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v1.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-south-1
          function_name: LauntriServ
          zip_file: lambda.zip
