name: Publish Website to cPanel

on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    name: FTP Deploy Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install  # Or 'yarn install' if you're using Yarn

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Deploy the whole repository or a specific directory
